#include "LuaBlueprint/LuaBlueprintCompiler.h"

#include "LuaBlueprint/LuaBlueprintAsset.h"

#include <algorithm>
#include <cstdio>
#include <sstream>
#include <unordered_map>
#include <unordered_set>
#include <utility>

namespace
{
	FString EscapeLuaString(const FString& In)
	{
		FString Out;
		Out.reserve(In.size() + 8);
		for (char Ch : In)
		{
			switch (Ch)
			{
			case '\\': Out += "\\\\"; break;
			case '"':  Out += "\\\""; break;
			case '\n': Out += "\\n"; break;
			case '\r': Out += "\\r"; break;
			case '\t': Out += "\\t"; break;
			default:   Out += Ch; break;
			}
		}
		return Out;
	}

	FString LuaQuoted(const FString& In)
	{
		return FString("\"") + EscapeLuaString(In) + "\"";
	}

	FString LuaName(const FName& Name)
	{
		return Name == FName::None ? FString() : Name.ToString();
	}

	const FLuaBlueprintPin* FindPinByName(const FLuaBlueprintNode& Node, const char* Name, ELuaBlueprintPinKind Kind)
	{
		for (const FLuaBlueprintPin& Pin : Node.Pins)
		{
			if (Pin.Kind == Kind && Pin.DisplayName.ToString() == Name)
			{
				return &Pin;
			}
		}
		return nullptr;
	}

	const FLuaBlueprintPin* FindFirstExecOutput(const FLuaBlueprintNode& Node)
	{
		for (const FLuaBlueprintPin& Pin : Node.Pins)
		{
			if (Pin.Kind == ELuaBlueprintPinKind::Output && Pin.Type == ELuaBlueprintPinType::Exec)
			{
				return &Pin;
			}
		}
		return nullptr;
	}

	const FLuaBlueprintPin* FindFirstValueOutput(const FLuaBlueprintNode& Node)
	{
		for (const FLuaBlueprintPin& Pin : Node.Pins)
		{
			if (Pin.Kind == ELuaBlueprintPinKind::Output && Pin.Type != ELuaBlueprintPinType::Exec)
			{
				return &Pin;
			}
		}
		return nullptr;
	}

	void AddDiagnostic(
		FLuaBlueprintCompileResult& Result,
		ELuaBlueprintDiagnosticSeverity Severity,
		uint32 NodeId,
		const FString& Message)
	{
		FLuaBlueprintDiagnostic Diagnostic;
		Diagnostic.Severity = Severity;
		Diagnostic.NodeId = NodeId;
		Diagnostic.Message = Message;
		Result.Diagnostics.push_back(std::move(Diagnostic));
		if (Severity == ELuaBlueprintDiagnosticSeverity::Error)
		{
			Result.bSuccess = false;
		}
	}

	class FCompilerContext
	{
	public:
		FCompilerContext(const ULuaBlueprintAsset& InAsset, FLuaBlueprintCompileResult& InResult)
			: Asset(InAsset), Result(InResult)
		{
			Result.bSuccess = true;
		}

		FString Compile()
		{
			std::ostringstream Out;
			Out << "-- Generated by Lua Blueprint compiler. Do not edit runtime output directly.\n";
			Out << "__vars = __vars or {}\n";
			EmitVariableInitializers(Out);
			Out << "\n";

			EmitEventFunction(Out, ELuaBlueprintNodeType::EventBeginPlay, "BeginPlay", "");
			EmitEventFunction(Out, ELuaBlueprintNodeType::EventTick, "Tick", "DeltaTime");
			EmitEventFunction(Out, ELuaBlueprintNodeType::EventEndPlay, "EndPlay", "");
			EmitEventFunction(Out, ELuaBlueprintNodeType::EventOverlap, "OnOverlap", "OtherActor, OverlappedComponent, OtherComp");
			EmitEventFunction(Out, ELuaBlueprintNodeType::EventEndOverlap, "OnEndOverlap", "OtherActor, OverlappedComponent, OtherComp");
			EmitEventFunction(Out, ELuaBlueprintNodeType::EventHit, "OnHit", "OtherActor, HitComponent, OtherComp, NormalImpulse, HitResult");
			EmitEventFunction(Out, ELuaBlueprintNodeType::EventEndHit, "OnEndHit", "OtherActor, HitComponent, OtherComp");

			return Out.str();
		}

		// Loop body 가 자기 자신을 통해 다시 들어오는 (Branch 의 True 가 같은 노드로) 시각적 cycle 은
		// 정상이지만, 실제 데이터 cycle 은 막아야 한다. ExecStack 으로 호출 stack 만 추적하면
		// 같은 노드를 서로 다른 path 로 emit 할 때 false-positive 가 난다 — 매 호출마다 입력 시 push,
		// 출력 시 pop 으로 충분히 처리됨.

	private:
		void EmitVariableInitializers(std::ostringstream& Out)
		{
			for (const FLuaBlueprintVariable& Variable : Asset.GetVariables())
			{
				const FString Name = LuaName(Variable.Name);
				if (Name.empty())
				{
					AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Warning, 0, "Variable with empty name was skipped");
					continue;
				}
				Out << "if __vars[" << LuaQuoted(Name) << "] == nil then __vars[" << LuaQuoted(Name) << "] = "
					<< LiteralForVariable(Variable) << " end\n";
			}
		}

		FString LiteralForVariable(const FLuaBlueprintVariable& Variable) const
		{
			switch (Variable.Type)
			{
			case ELuaBlueprintPinType::Bool:   return Variable.BoolValue ? "true" : "false";
			case ELuaBlueprintPinType::Int:    return std::to_string(Variable.IntValue);
			case ELuaBlueprintPinType::Float:  return FormatFloat(Variable.FloatValue);
			case ELuaBlueprintPinType::String: return LuaQuoted(Variable.StringValue);
			case ELuaBlueprintPinType::Vector: return FormatVector(Variable.VectorValue);
			case ELuaBlueprintPinType::Object: return "nil";
			default:                          return "nil";
			}
		}

		void EmitEventFunction(std::ostringstream& Out, ELuaBlueprintNodeType EventType, const char* FunctionName, const char* Args)
		{
			const FLuaBlueprintNode* Event = FindFirstNodeOfType(EventType);
			Out << "function " << FunctionName << "(" << Args << ")\n";
			if (Event)
			{
				std::unordered_set<uint32> ExecStack;
				if (const FLuaBlueprintPin* Then = FindFirstExecOutput(*Event))
				{
					EmitNextExecFromPin(Out, Then->PinId, 1, ExecStack);
				}
			}
			Out << "end\n\n";
		}

		const FLuaBlueprintNode* FindFirstNodeOfType(ELuaBlueprintNodeType Type) const
		{
			for (const FLuaBlueprintNode& Node : Asset.GetNodes())
			{
				if (Node.Type == Type) return &Node;
			}
			return nullptr;
		}

		void EmitNextExecFromPin(std::ostringstream& Out, uint32 OutputPinId, int Indent, std::unordered_set<uint32>& ExecStack)
		{
			const FLuaBlueprintLink* Link = Asset.FindFirstLinkFromOutput(OutputPinId);
			if (!Link) return;

			const FLuaBlueprintPin* InputPin = Asset.FindPin(Link->ToPinId);
			if (!InputPin) return;

			const FLuaBlueprintNode* Node = Asset.FindNode(InputPin->OwningNodeId);
			if (!Node) return;

			EmitExecNode(Out, *Node, Indent, ExecStack);
		}

		void EmitExecNode(std::ostringstream& Out, const FLuaBlueprintNode& Node, int Indent, std::unordered_set<uint32>& ExecStack)
		{
			if (ExecStack.find(Node.NodeId) != ExecStack.end())
			{
				AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "Exec cycle detected");
				EmitIndent(Out, Indent);
				Out << "-- compile error: exec cycle detected at node " << Node.NodeId << "\n";
				return;
			}

			ExecStack.insert(Node.NodeId);
			switch (Node.Type)
			{
			case ELuaBlueprintNodeType::Sequence:
				EmitSequence(Out, Node, Indent, ExecStack);
				break;
			case ELuaBlueprintNodeType::Branch:
				EmitBranch(Out, Node, Indent, ExecStack);
				break;
			case ELuaBlueprintNodeType::ForLoop:
				EmitForLoop(Out, Node, Indent, ExecStack);
				break;
			case ELuaBlueprintNodeType::WhileLoop:
				EmitWhileLoop(Out, Node, Indent, ExecStack);
				break;
			case ELuaBlueprintNodeType::PrintString:
				EmitIndent(Out, Indent);
				Out << "print(tostring(" << GetInputExpression(Node, "Text", LuaQuoted(Node.StringValue)) << "))\n";
				EmitThen(Out, Node, Indent, ExecStack);
				break;
			case ELuaBlueprintNodeType::SetVariable:
				EmitSetVariable(Out, Node, Indent, ExecStack);
				break;
			case ELuaBlueprintNodeType::SetProperty:
				EmitSetProperty(Out, Node, Indent, ExecStack);
				break;
			case ELuaBlueprintNodeType::CallFunction:
			case ELuaBlueprintNodeType::CallFunctionSignature:
				EmitCallFunction(Out, Node, Indent, ExecStack);
				break;

			case ELuaBlueprintNodeType::SpawnActor:                EmitSpawnActor(Out, Node, Indent, ExecStack); break;
			case ELuaBlueprintNodeType::DestroyActor:              EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Target} then ({Target}):Destroy() end"); break;
			case ELuaBlueprintNodeType::SetActorLocation:          EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Target} then ({Target}).Location = {Value} end"); break;
			case ELuaBlueprintNodeType::SetActorRotation:          EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Target} then ({Target}).Rotation = {Value} end"); break;
			case ELuaBlueprintNodeType::SetActorScale:             EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Target} then ({Target}).Scale = {Value} end"); break;
			case ELuaBlueprintNodeType::AddActorWorldOffset:       EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Target} then ({Target}):AddWorldOffset({Value}) end"); break;
			case ELuaBlueprintNodeType::ActorAddTag:               EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Target} then ({Target}):AddTag({Tag}) end"); break;
			case ELuaBlueprintNodeType::ActorRemoveTag:            EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Target} then ({Target}):RemoveTag({Tag}) end"); break;
			case ELuaBlueprintNodeType::ActivateComponent:         EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Component} then ({Component}):Activate() end"); break;
			case ELuaBlueprintNodeType::DeactivateComponent:       EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Component} then ({Component}):Deactivate() end"); break;
			case ELuaBlueprintNodeType::AddForce:                  EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Component} then ({Component}):AddForce({Vector}) end"); break;
			case ELuaBlueprintNodeType::AddTorque:                 EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Component} then ({Component}):AddTorque({Vector}) end"); break;
			case ELuaBlueprintNodeType::SetLinearVelocity:         EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Component} then ({Component}):SetLinearVelocity({Velocity}) end"); break;
			case ELuaBlueprintNodeType::SetSimulatePhysics:        EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Component} then ({Component}):SetSimulatePhysics({Simulate}) end"); break;

			case ELuaBlueprintNodeType::Cast:                      EmitCast(Out, Node, Indent, ExecStack); break;
			case ELuaBlueprintNodeType::ForEachActorByClass:       EmitForEachActor(Out, Node, Indent, ExecStack, /*bByClass*/true); break;
			case ELuaBlueprintNodeType::ForEachActorByTag:         EmitForEachActor(Out, Node, Indent, ExecStack, /*bByClass*/false); break;

			default:
				AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Warning, Node.NodeId, "Node is not executable and was skipped");
				EmitThen(Out, Node, Indent, ExecStack);
				break;
			}
			ExecStack.erase(Node.NodeId);
		}

		void EmitForLoop(std::ostringstream& Out, const FLuaBlueprintNode& Node, int Indent, std::unordered_set<uint32>& ExecStack)
		{
			const FString First = GetInputExpression(Node, "First", "0");
			const FString Last  = GetInputExpression(Node, "Last", "0");
			EmitIndent(Out, Indent);
			Out << "for __i = " << First << ", " << Last << " do\n";
			LoopIndexNodeIds[Node.NodeId] = "__i";
			if (const FLuaBlueprintPin* Loop = FindPinByName(Node, "Loop", ELuaBlueprintPinKind::Output))
			{
				EmitNextExecFromPin(Out, Loop->PinId, Indent + 1, ExecStack);
			}
			LoopIndexNodeIds.erase(Node.NodeId);
			EmitIndent(Out, Indent);
			Out << "end\n";
			if (const FLuaBlueprintPin* Done = FindPinByName(Node, "Completed", ELuaBlueprintPinKind::Output))
			{
				EmitNextExecFromPin(Out, Done->PinId, Indent, ExecStack);
			}
		}

		void EmitWhileLoop(std::ostringstream& Out, const FLuaBlueprintNode& Node, int Indent, std::unordered_set<uint32>& ExecStack)
		{
			EmitIndent(Out, Indent);
			Out << "while " << GetInputExpression(Node, "Condition", "false") << " do\n";
			if (const FLuaBlueprintPin* Loop = FindPinByName(Node, "Loop", ELuaBlueprintPinKind::Output))
			{
				EmitNextExecFromPin(Out, Loop->PinId, Indent + 1, ExecStack);
			}
			EmitIndent(Out, Indent);
			Out << "end\n";
			if (const FLuaBlueprintPin* Done = FindPinByName(Node, "Completed", ELuaBlueprintPinKind::Output))
			{
				EmitNextExecFromPin(Out, Done->PinId, Indent, ExecStack);
			}
		}

		// SpawnActor 는 데이터 output("Actor") 도 있으므로 실행 시 local 에 결과를 보관 후 EmitThen.
		// 하류 노드의 GetOutputExpression 은 ExecLocals 에서 이 local 을 읽는다.
		void EmitSpawnActor(std::ostringstream& Out, const FLuaBlueprintNode& Node, int Indent, std::unordered_set<uint32>& ExecStack)
		{
			const FString ClassName = LuaName(Node.NameValue);
			if (ClassName.empty())
			{
				AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "SpawnActor has no class name");
				return;
			}
			const FString Local = FString("__n") + std::to_string(Node.NodeId);
			EmitIndent(Out, Indent);
			Out << "local " << Local << " = World.SpawnActor(" << LuaQuoted(ClassName) << ")\n";
			ExecLocals[Node.NodeId] = Local;
			EmitThen(Out, Node, Indent, ExecStack);
			ExecLocals.erase(Node.NodeId);
		}

		// {PinName} 형태의 placeholder 를 GetInputExpression 으로 치환해 한 줄짜리 statement 를 emit.
		// 단순 wrapper exec 노드 (DestroyActor, AddForce, SetActorLocation 등) 공통.
		void EmitSimpleCall(std::ostringstream& Out, const FLuaBlueprintNode& Node, int Indent, std::unordered_set<uint32>& ExecStack, const FString& Template)
		{
			FString Line = Template;
			// 핀별로 {PinName} 치환. Exec/Object/Vector/Float/Bool 등 모두 대상.
			for (const FLuaBlueprintPin& Pin : Node.Pins)
			{
				if (Pin.Kind != ELuaBlueprintPinKind::Input) continue;
				if (Pin.Type == ELuaBlueprintPinType::Exec) continue;
				const FString PlaceholderToken = FString("{") + Pin.DisplayName.ToString() + "}";
				const FString Value = GetInputExpression(Node, Pin.DisplayName.ToString().c_str(), "nil");
				// 단순 string replace — 같은 placeholder 가 여러 번 나올 수 있으므로 loop.
				size_t Pos = 0;
				while ((Pos = Line.find(PlaceholderToken, Pos)) != FString::npos)
				{
					Line.replace(Pos, PlaceholderToken.size(), Value);
					Pos += Value.size();
				}
			}
			EmitIndent(Out, Indent);
			Out << Line << "\n";
			EmitThen(Out, Node, Indent, ExecStack);
		}

		// Cast: Success/Failed exec 분기. Result 데이터 output 은 Success 경로에서만 유효.
		void EmitCast(std::ostringstream& Out, const FLuaBlueprintNode& Node, int Indent, std::unordered_set<uint32>& ExecStack)
		{
			const FString ClassName = LuaName(Node.NameValue);
			if (ClassName.empty())
			{
				AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "Cast has no class name");
				return;
			}
			const FString Local = FString("__c") + std::to_string(Node.NodeId);
			EmitIndent(Out, Indent);
			Out << "local " << Local << " = Reflection.Cast(" << GetInputExpression(Node, "Target", "nil") << ", " << LuaQuoted(ClassName) << ")\n";

			EmitIndent(Out, Indent);
			Out << "if " << Local << " ~= nil then\n";
			ExecLocals[Node.NodeId] = Local;
			if (const FLuaBlueprintPin* Success = FindPinByName(Node, "Success", ELuaBlueprintPinKind::Output))
			{
				EmitNextExecFromPin(Out, Success->PinId, Indent + 1, ExecStack);
			}
			ExecLocals.erase(Node.NodeId);
			EmitIndent(Out, Indent);
			Out << "else\n";
			if (const FLuaBlueprintPin* Failed = FindPinByName(Node, "Failed", ELuaBlueprintPinKind::Output))
			{
				EmitNextExecFromPin(Out, Failed->PinId, Indent + 1, ExecStack);
			}
			EmitIndent(Out, Indent);
			Out << "end\n";
		}

		// ForEachActor — class 또는 tag 기반. iteration 동안 Actor pin/Index pin 매핑 set.
		void EmitForEachActor(std::ostringstream& Out, const FLuaBlueprintNode& Node, int Indent, std::unordered_set<uint32>& ExecStack, bool bByClass)
		{
			const FString Key = bByClass ? LuaName(Node.NameValue) : Node.StringValue;
			if (Key.empty())
			{
				AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, bByClass
					? "ForEachActor has no class name"
					: "ForEachActor has no tag");
				return;
			}
			const FString ActorLocal = FString("__a") + std::to_string(Node.NodeId);
			const FString IndexLocal = FString("__i") + std::to_string(Node.NodeId);
			const char*   Source     = bByClass ? "World.FindActorsByClass" : "World.FindActorsByTag";

			EmitIndent(Out, Indent);
			Out << "for " << IndexLocal << ", " << ActorLocal << " in ipairs(" << Source << "(" << LuaQuoted(Key) << ")) do\n";
			ForEachActorNodeIds[Node.NodeId] = ActorLocal;
			LoopIndexNodeIds[Node.NodeId]    = IndexLocal;
			if (const FLuaBlueprintPin* Loop = FindPinByName(Node, "Loop", ELuaBlueprintPinKind::Output))
			{
				EmitNextExecFromPin(Out, Loop->PinId, Indent + 1, ExecStack);
			}
			ForEachActorNodeIds.erase(Node.NodeId);
			LoopIndexNodeIds.erase(Node.NodeId);
			EmitIndent(Out, Indent);
			Out << "end\n";
			if (const FLuaBlueprintPin* Done = FindPinByName(Node, "Completed", ELuaBlueprintPinKind::Output))
			{
				EmitNextExecFromPin(Out, Done->PinId, Indent, ExecStack);
			}
		}

		void EmitSequence(std::ostringstream& Out, const FLuaBlueprintNode& Node, int Indent, std::unordered_set<uint32>& ExecStack)
		{
			TArray<const FLuaBlueprintPin*> Outputs;
			for (const FLuaBlueprintPin& Pin : Node.Pins)
			{
				if (Pin.Kind == ELuaBlueprintPinKind::Output && Pin.Type == ELuaBlueprintPinType::Exec)
				{
					Outputs.push_back(&Pin);
				}
			}
			std::sort(Outputs.begin(), Outputs.end(), [](const FLuaBlueprintPin* A, const FLuaBlueprintPin* B)
			{
				return A->DisplayName.ToString() < B->DisplayName.ToString();
			});
			for (const FLuaBlueprintPin* Pin : Outputs)
			{
				EmitNextExecFromPin(Out, Pin->PinId, Indent, ExecStack);
			}
		}

		void EmitBranch(std::ostringstream& Out, const FLuaBlueprintNode& Node, int Indent, std::unordered_set<uint32>& ExecStack)
		{
			EmitIndent(Out, Indent);
			Out << "if " << GetInputExpression(Node, "Condition", "false") << " then\n";
			if (const FLuaBlueprintPin* TruePin = FindPinByName(Node, "True", ELuaBlueprintPinKind::Output))
			{
				EmitNextExecFromPin(Out, TruePin->PinId, Indent + 1, ExecStack);
			}
			EmitIndent(Out, Indent);
			Out << "else\n";
			if (const FLuaBlueprintPin* FalsePin = FindPinByName(Node, "False", ELuaBlueprintPinKind::Output))
			{
				EmitNextExecFromPin(Out, FalsePin->PinId, Indent + 1, ExecStack);
			}
			EmitIndent(Out, Indent);
			Out << "end\n";
		}

		void EmitSetVariable(std::ostringstream& Out, const FLuaBlueprintNode& Node, int Indent, std::unordered_set<uint32>& ExecStack)
		{
			const FString VarName = LuaName(Node.NameValue);
			if (VarName.empty())
			{
				AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "SetVariable has no variable name");
				return;
			}
			EmitIndent(Out, Indent);
			Out << "__vars[" << LuaQuoted(VarName) << "] = " << GetInputExpression(Node, "Value", "nil") << "\n";
			EmitThen(Out, Node, Indent, ExecStack);
		}

		void EmitSetProperty(std::ostringstream& Out, const FLuaBlueprintNode& Node, int Indent, std::unordered_set<uint32>& ExecStack)
		{
			const FString PropertyName = LuaName(Node.NameValue);
			if (PropertyName.empty())
			{
				AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "SetProperty has no property name");
				return;
			}
			EmitIndent(Out, Indent);
			Out << "Reflection.SetProperty(" << GetInputExpression(Node, "Target", "obj") << ", "
				<< LuaQuoted(PropertyName) << ", " << GetInputExpression(Node, "Value", "nil") << ")\n";
			EmitThen(Out, Node, Indent, ExecStack);
		}

		void EmitCallFunction(std::ostringstream& Out, const FLuaBlueprintNode& Node, int Indent, std::unordered_set<uint32>& ExecStack)
		{
			const FString Target = GetInputExpression(Node, "Target", "obj");
			const FString Name = (Node.Type == ELuaBlueprintNodeType::CallFunctionSignature)
				? (!Node.StringValue.empty() ? Node.StringValue : LuaName(Node.NameValue))
				: LuaName(Node.NameValue);

			if (Name.empty())
			{
				AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "CallFunction has no function name/signature");
				return;
			}

			EmitIndent(Out, Indent);
			Out << MakeCallExpression(Node, Target, Name) << "\n";
			EmitThen(Out, Node, Indent, ExecStack);
		}

		void EmitThen(std::ostringstream& Out, const FLuaBlueprintNode& Node, int Indent, std::unordered_set<uint32>& ExecStack)
		{
			if (const FLuaBlueprintPin* Then = FindFirstExecOutput(Node))
			{
				EmitNextExecFromPin(Out, Then->PinId, Indent, ExecStack);
			}
		}

		FString GetInputExpression(const FLuaBlueprintNode& Node, const char* PinName, const FString& DefaultExpr)
		{
			const FLuaBlueprintPin* InputPin = FindPinByName(Node, PinName, ELuaBlueprintPinKind::Input);
			if (!InputPin)
			{
				return DefaultExpr;
			}

			const FLuaBlueprintLink* Link = Asset.FindLinkToInput(InputPin->PinId);
			if (!Link)
			{
				// 연결이 없으면 핀의 inline literal 사용 (실제 Blueprint 동작).
				return PinDefaultExpression(*InputPin, DefaultExpr);
			}

			const FLuaBlueprintPin* SourcePin = Asset.FindPin(Link->FromPinId);
			if (!SourcePin)
			{
				return DefaultExpr;
			}

			const FLuaBlueprintNode* SourceNode = Asset.FindNode(SourcePin->OwningNodeId);
			if (!SourceNode)
			{
				return DefaultExpr;
			}

			return GetOutputExpression(*SourceNode, *SourcePin);
		}

		FString PinDefaultExpression(const FLuaBlueprintPin& Pin, const FString& Fallback) const
		{
			switch (Pin.Type)
			{
			case ELuaBlueprintPinType::Bool:   return Pin.DefaultBool ? "true" : "false";
			case ELuaBlueprintPinType::Int:    return std::to_string(Pin.DefaultInt);
			case ELuaBlueprintPinType::Float:  return FormatFloat(Pin.DefaultFloat);
			case ELuaBlueprintPinType::String: return LuaQuoted(Pin.DefaultString);
			case ELuaBlueprintPinType::Vector: return FormatVector(Pin.DefaultVector);
			case ELuaBlueprintPinType::Object: return "nil";
			case ELuaBlueprintPinType::Any:
			case ELuaBlueprintPinType::Exec:
			default:                           return Fallback;
			}
		}

		FString GetOutputExpression(const FLuaBlueprintNode& Node, const FLuaBlueprintPin& OutputPin)
		{
			(void)OutputPin;
			switch (Node.Type)
			{
			case ELuaBlueprintNodeType::EventTick:
				return OutputPin.DisplayName.ToString() == "DeltaTime" ? FString("DeltaTime") : FString("nil");
			case ELuaBlueprintNodeType::EventOverlap:
			case ELuaBlueprintNodeType::EventEndOverlap:
			case ELuaBlueprintNodeType::EventHit:
			case ELuaBlueprintNodeType::EventEndHit:
				return OutputPin.DisplayName.ToString();
			case ELuaBlueprintNodeType::LiteralBool:
				return Node.BoolValue ? "true" : "false";
			case ELuaBlueprintNodeType::LiteralInt:
				return std::to_string(Node.IntValue);
			case ELuaBlueprintNodeType::LiteralFloat:
				return FormatFloat(Node.FloatValue);
			case ELuaBlueprintNodeType::LiteralString:
				return LuaQuoted(Node.StringValue);
			case ELuaBlueprintNodeType::LiteralVector:
				return FormatVector(Node.VectorValue);
			case ELuaBlueprintNodeType::GetVariable:
			{
				const FString VarName = LuaName(Node.NameValue);
				if (VarName.empty())
				{
					AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "GetVariable has no variable name");
					return "nil";
				}
				return FString("__vars[") + LuaQuoted(VarName) + "]";
			}
			case ELuaBlueprintNodeType::GetProperty:
			{
				const FString PropertyName = LuaName(Node.NameValue);
				if (PropertyName.empty())
				{
					AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "GetProperty has no property name");
					return "nil";
				}
				return FString("Reflection.GetProperty(") + GetInputExpression(Node, "Target", "obj") + ", " + LuaQuoted(PropertyName) + ")";
			}
			case ELuaBlueprintNodeType::CallFunction:
			case ELuaBlueprintNodeType::CallFunctionSignature:
			{
				const FString Name = (Node.Type == ELuaBlueprintNodeType::CallFunctionSignature)
					? (!Node.StringValue.empty() ? Node.StringValue : LuaName(Node.NameValue))
					: LuaName(Node.NameValue);
				if (Name.empty()) return "nil";
				return MakeCallExpression(Node, GetInputExpression(Node, "Target", "obj"), Name);
			}
			case ELuaBlueprintNodeType::AddFloat:
				return FString("(") + GetInputExpression(Node, "A", "0") + " + " + GetInputExpression(Node, "B", "0") + ")";
			case ELuaBlueprintNodeType::SubtractFloat:
				return FString("(") + GetInputExpression(Node, "A", "0") + " - " + GetInputExpression(Node, "B", "0") + ")";
			case ELuaBlueprintNodeType::MultiplyFloat:
				return FString("(") + GetInputExpression(Node, "A", "0") + " * " + GetInputExpression(Node, "B", "0") + ")";
			case ELuaBlueprintNodeType::DivideFloat:
				return FString("(") + GetInputExpression(Node, "A", "0") + " / " + GetInputExpression(Node, "B", "1") + ")";
			case ELuaBlueprintNodeType::AddInt:
				return FString("(") + GetInputExpression(Node, "A", "0") + " + " + GetInputExpression(Node, "B", "0") + ")";
			case ELuaBlueprintNodeType::SubtractInt:
				return FString("(") + GetInputExpression(Node, "A", "0") + " - " + GetInputExpression(Node, "B", "0") + ")";
			case ELuaBlueprintNodeType::MultiplyInt:
				return FString("(") + GetInputExpression(Node, "A", "0") + " * " + GetInputExpression(Node, "B", "0") + ")";
			case ELuaBlueprintNodeType::DivideInt:
				// math.floor 로 truncate — Lua 정수 나눗셈은 5.3 부터 // 연산자, 호환성 위해 floor 사용.
				return FString("math.floor(") + GetInputExpression(Node, "A", "0") + " / " + GetInputExpression(Node, "B", "1") + ")";
			case ELuaBlueprintNodeType::ModInt:
				return FString("(") + GetInputExpression(Node, "A", "0") + " % " + GetInputExpression(Node, "B", "1") + ")";
			case ELuaBlueprintNodeType::EqualFloat:
			case ELuaBlueprintNodeType::EqualInt:
				return FString("(") + GetInputExpression(Node, "A", "0") + " == " + GetInputExpression(Node, "B", "0") + ")";
			case ELuaBlueprintNodeType::NotEqualFloat:
			case ELuaBlueprintNodeType::NotEqualInt:
				return FString("(") + GetInputExpression(Node, "A", "0") + " ~= " + GetInputExpression(Node, "B", "0") + ")";
			case ELuaBlueprintNodeType::LessFloat:
			case ELuaBlueprintNodeType::LessInt:
				return FString("(") + GetInputExpression(Node, "A", "0") + " < " + GetInputExpression(Node, "B", "0") + ")";
			case ELuaBlueprintNodeType::GreaterFloat:
			case ELuaBlueprintNodeType::GreaterInt:
				return FString("(") + GetInputExpression(Node, "A", "0") + " > " + GetInputExpression(Node, "B", "0") + ")";
			case ELuaBlueprintNodeType::LessEqualFloat:
				return FString("(") + GetInputExpression(Node, "A", "0") + " <= " + GetInputExpression(Node, "B", "0") + ")";
			case ELuaBlueprintNodeType::GreaterEqualFloat:
				return FString("(") + GetInputExpression(Node, "A", "0") + " >= " + GetInputExpression(Node, "B", "0") + ")";
			case ELuaBlueprintNodeType::And:
				return FString("(") + GetInputExpression(Node, "A", "false") + " and " + GetInputExpression(Node, "B", "false") + ")";
			case ELuaBlueprintNodeType::Or:
				return FString("(") + GetInputExpression(Node, "A", "false") + " or " + GetInputExpression(Node, "B", "false") + ")";
			case ELuaBlueprintNodeType::Not:
				return FString("(not ") + GetInputExpression(Node, "A", "false") + ")";
			case ELuaBlueprintNodeType::AppendString:
				// tostring 으로 감싸 숫자/bool 도 안전.
				return FString("(tostring(") + GetInputExpression(Node, "A", "\"\"") + ") .. tostring(" + GetInputExpression(Node, "B", "\"\"") + "))";
			case ELuaBlueprintNodeType::MakeVector:
				return FString("Vector(") + GetInputExpression(Node, "X", "0") + ", " + GetInputExpression(Node, "Y", "0") + ", " + GetInputExpression(Node, "Z", "0") + ")";
			case ELuaBlueprintNodeType::BreakVector:
			{
				const FString V = GetInputExpression(Node, "V", "Vector(0,0,0)");
				const FString Name = OutputPin.DisplayName.ToString();
				if (Name == "X" || Name == "Y" || Name == "Z")
				{
					return FString("((") + V + ")." + Name + ")";
				}
				return "0";
			}
			case ELuaBlueprintNodeType::AddVector:
				return FString("((") + GetInputExpression(Node, "A", "Vector(0,0,0)") + ") + (" + GetInputExpression(Node, "B", "Vector(0,0,0)") + "))";
			case ELuaBlueprintNodeType::SubtractVector:
				return FString("((") + GetInputExpression(Node, "A", "Vector(0,0,0)") + ") - (" + GetInputExpression(Node, "B", "Vector(0,0,0)") + "))";
			case ELuaBlueprintNodeType::ScaleVector:
				return FString("((") + GetInputExpression(Node, "V", "Vector(0,0,0)") + ") * (" + GetInputExpression(Node, "Scale", "1") + "))";
			case ELuaBlueprintNodeType::DotVector:
				return FString("((") + GetInputExpression(Node, "A", "Vector(0,0,0)") + "):Dot(" + GetInputExpression(Node, "B", "Vector(0,0,0)") + "))";
			case ELuaBlueprintNodeType::CrossVector:
				return FString("((") + GetInputExpression(Node, "A", "Vector(0,0,0)") + "):Cross(" + GetInputExpression(Node, "B", "Vector(0,0,0)") + "))";
			case ELuaBlueprintNodeType::VectorLength:
				return FString("((") + GetInputExpression(Node, "V", "Vector(0,0,0)") + "):Length())";
			case ELuaBlueprintNodeType::NormalizeVector:
				return FString("((") + GetInputExpression(Node, "V", "Vector(0,0,0)") + "):Normalized())";
			case ELuaBlueprintNodeType::Self:
				return "obj";
			case ELuaBlueprintNodeType::ForLoop:
			{
				if (OutputPin.DisplayName.ToString() == "Index")
				{
					auto It = LoopIndexNodeIds.find(Node.NodeId);
					return (It != LoopIndexNodeIds.end()) ? It->second : FString("0");
				}
				return "nil";
			}

			// ── Actor find / accessors ──
			case ELuaBlueprintNodeType::SpawnActor:
			case ELuaBlueprintNodeType::Cast:
			{
				auto It = ExecLocals.find(Node.NodeId);
				return It != ExecLocals.end() ? It->second : FString("nil");
			}
			case ELuaBlueprintNodeType::FindActorByName:
				return FString("World.FindActorByName(") + GetInputExpression(Node, "Name", LuaQuoted(Node.StringValue)) + ")";
			case ELuaBlueprintNodeType::FindActorByClass:
				return FString("World.FindFirstActorByClass(") + LuaQuoted(LuaName(Node.NameValue)) + ")";
			case ELuaBlueprintNodeType::FindActorByTag:
				return FString("World.FindFirstActorByTag(") + GetInputExpression(Node, "Tag", LuaQuoted(Node.StringValue)) + ")";
			case ELuaBlueprintNodeType::FindActorsByTag:
				return FString("World.FindActorsByTag(") + GetInputExpression(Node, "Tag", LuaQuoted(Node.StringValue)) + ")";
			case ELuaBlueprintNodeType::FindActorsByClass:
				return FString("World.FindActorsByClass(") + LuaQuoted(LuaName(Node.NameValue)) + ")";
			case ELuaBlueprintNodeType::GetActorLocation:
				return FString("(") + GetInputExpression(Node, "Target", "obj") + " and (" + GetInputExpression(Node, "Target", "obj") + ").Location or Vector(0,0,0))";
			case ELuaBlueprintNodeType::GetActorRotation:
				return FString("(") + GetInputExpression(Node, "Target", "obj") + " and (" + GetInputExpression(Node, "Target", "obj") + ").Rotation or Vector(0,0,0))";
			case ELuaBlueprintNodeType::GetActorScale:
				return FString("(") + GetInputExpression(Node, "Target", "obj") + " and (" + GetInputExpression(Node, "Target", "obj") + ").Scale or Vector(1,1,1))";
			case ELuaBlueprintNodeType::GetActorForward:
				return FString("(") + GetInputExpression(Node, "Target", "obj") + " and (" + GetInputExpression(Node, "Target", "obj") + ").Forward or Vector(1,0,0))";
			case ELuaBlueprintNodeType::GetActorRight:
				return FString("(") + GetInputExpression(Node, "Target", "obj") + " and (" + GetInputExpression(Node, "Target", "obj") + ").Right or Vector(0,1,0))";
			case ELuaBlueprintNodeType::ActorHasTag:
				return FString("(") + GetInputExpression(Node, "Target", "obj") + " and (" + GetInputExpression(Node, "Target", "obj") + "):HasTag(" + GetInputExpression(Node, "Tag", LuaQuoted("")) + ") or false)";
			case ELuaBlueprintNodeType::GetActorName:
				return FString("(") + GetInputExpression(Node, "Target", "obj") + " and (" + GetInputExpression(Node, "Target", "obj") + ").Name or \"\")";
			case ELuaBlueprintNodeType::GetOwnerActor:
				return FString("(") + GetInputExpression(Node, "Component", "nil") + " and (" + GetInputExpression(Node, "Component", "nil") + "):GetOwner() or nil)";

			// ── Object utility ──
			case ELuaBlueprintNodeType::IsValid:
			{
				const FString Target = GetInputExpression(Node, "Target", "nil");
				return FString("(") + Target + " ~= nil and (" + Target + "):IsValid())";
			}

			// ── Component getters ──
			case ELuaBlueprintNodeType::GetRootComponent:
				return FString("(") + GetInputExpression(Node, "Actor", "obj") + " and (" + GetInputExpression(Node, "Actor", "obj") + "):GetRootPrimitiveComponent() or nil)";
			case ELuaBlueprintNodeType::GetComponentByName:
				return FString("(") + GetInputExpression(Node, "Actor", "obj") + " and (" + GetInputExpression(Node, "Actor", "obj") + "):GetComponentByName(" + GetInputExpression(Node, "Name", LuaQuoted(Node.StringValue)) + ") or nil)";
			case ELuaBlueprintNodeType::GetPrimitiveComponent:
				return FString("(") + GetInputExpression(Node, "Actor", "obj") + " and (" + GetInputExpression(Node, "Actor", "obj") + "):GetPrimitiveComponent() or nil)";
			case ELuaBlueprintNodeType::GetLinearVelocity:
				return FString("(") + GetInputExpression(Node, "Component", "nil") + " and (" + GetInputExpression(Node, "Component", "nil") + "):GetLinearVelocity() or Vector(0,0,0))";
			case ELuaBlueprintNodeType::GetMass:
				return FString("(") + GetInputExpression(Node, "Component", "nil") + " and (" + GetInputExpression(Node, "Component", "nil") + "):GetMass() or 0)";

			// ── Math util ──
			case ELuaBlueprintNodeType::Lerp:
			{
				const FString A = GetInputExpression(Node, "A", "0");
				const FString B = GetInputExpression(Node, "B", "0");
				const FString T = GetInputExpression(Node, "Alpha", "0");
				return FString("((1 - ") + T + ") * " + A + " + " + T + " * " + B + ")";
			}
			case ELuaBlueprintNodeType::Clamp:
				return FString("math.max(") + GetInputExpression(Node, "Min", "0") + ", math.min(" + GetInputExpression(Node, "Max", "0") + ", " + GetInputExpression(Node, "Value", "0") + "))";
			case ELuaBlueprintNodeType::Min:
				return FString("math.min(") + GetInputExpression(Node, "A", "0") + ", " + GetInputExpression(Node, "B", "0") + ")";
			case ELuaBlueprintNodeType::Max:
				return FString("math.max(") + GetInputExpression(Node, "A", "0") + ", " + GetInputExpression(Node, "B", "0") + ")";
			case ELuaBlueprintNodeType::RandomFloat:
			{
				const FString Lo = GetInputExpression(Node, "Min", "0");
				const FString Hi = GetInputExpression(Node, "Max", "1");
				return FString("(") + Lo + " + math.random() * (" + Hi + " - " + Lo + "))";
			}
			case ELuaBlueprintNodeType::RandomInt:
				return FString("math.random(") + GetInputExpression(Node, "Min", "0") + ", " + GetInputExpression(Node, "Max", "0") + ")";
			case ELuaBlueprintNodeType::Sin:
				return FString("math.sin(") + GetInputExpression(Node, "Value", "0") + ")";
			case ELuaBlueprintNodeType::Cos:
				return FString("math.cos(") + GetInputExpression(Node, "Value", "0") + ")";
			case ELuaBlueprintNodeType::Sqrt:
				return FString("math.sqrt(") + GetInputExpression(Node, "Value", "0") + ")";
			case ELuaBlueprintNodeType::AbsFloat:
				return FString("math.abs(") + GetInputExpression(Node, "Value", "0") + ")";
			case ELuaBlueprintNodeType::Floor:
				return FString("math.floor(") + GetInputExpression(Node, "Value", "0") + ")";
			case ELuaBlueprintNodeType::Ceil:
				return FString("math.ceil(") + GetInputExpression(Node, "Value", "0") + ")";
			case ELuaBlueprintNodeType::Distance:
				return FString("((") + GetInputExpression(Node, "A", "Vector(0,0,0)") + ") - (" + GetInputExpression(Node, "B", "Vector(0,0,0)") + ")):Length()";

			// ── Time ──
			case ELuaBlueprintNodeType::GetGameTime:
				return "World.GetGameTime()";

			// ── ForEachActor ──
			case ELuaBlueprintNodeType::ForEachActorByClass:
			case ELuaBlueprintNodeType::ForEachActorByTag:
			{
				const FString PinName = OutputPin.DisplayName.ToString();
				if (PinName == "Actor")
				{
					auto It = ForEachActorNodeIds.find(Node.NodeId);
					return It != ForEachActorNodeIds.end() ? It->second : FString("nil");
				}
				if (PinName == "Index")
				{
					auto It = LoopIndexNodeIds.find(Node.NodeId);
					return It != LoopIndexNodeIds.end() ? It->second : FString("0");
				}
				return "nil";
			}

			default:
				return "nil";
			}
		}

		FString MakeCallExpression(const FLuaBlueprintNode& Node, const FString& Target, const FString& Name)
		{
			TArray<std::pair<FString, FString>> Args;
			for (const FLuaBlueprintPin& Pin : Node.Pins)
			{
				if (Pin.Kind != ELuaBlueprintPinKind::Input || Pin.Type == ELuaBlueprintPinType::Exec)
				{
					continue;
				}

				const FString PinName = Pin.DisplayName.ToString();
				if (PinName.rfind("Arg", 0) != 0)
				{
					continue;
				}

				const FLuaBlueprintLink* Link = Asset.FindLinkToInput(Pin.PinId);
				if (!Link)
				{
					continue;
				}

				Args.push_back({ PinName, GetInputExpression(Node, PinName.c_str(), "nil") });
			}

			std::sort(Args.begin(), Args.end(), [](const auto& A, const auto& B)
			{
				return A.first < B.first;
			});

			FString Suffix;
			for (const auto& Arg : Args)
			{
				Suffix += ", ";
				Suffix += Arg.second;
			}

			if (Node.Type == ELuaBlueprintNodeType::CallFunctionSignature)
			{
				return FString("Reflection.CallSignature(") + Target + ", " + LuaQuoted(Name) + Suffix + ")";
			}
			return FString("Reflection.Call(") + Target + ", " + LuaQuoted(Name) + Suffix + ")";
		}

		void EmitIndent(std::ostringstream& Out, int Indent)
		{
			for (int I = 0; I < Indent; ++I)
			{
				Out << "    ";
			}
		}

		FString FormatFloat(float Value) const
		{
			char Buffer[64];
			std::snprintf(Buffer, sizeof(Buffer), "%.9g", Value);
			return Buffer;
		}

		FString FormatVector(const FVector& Value) const
		{
			return FString("Vector(") + FormatFloat(Value.X) + ", " + FormatFloat(Value.Y) + ", " + FormatFloat(Value.Z) + ")";
		}

	private:
		const ULuaBlueprintAsset& Asset;
		FLuaBlueprintCompileResult& Result;
		// 활성 ForLoop 노드 → 그 노드의 Index pin 을 reference 하는 코드. nested loop 시 stack 처럼 사용.
		std::unordered_map<uint32, FString> LoopIndexNodeIds;
		// ForEachActor 노드 → 현재 iteration 의 actor 변수명. 위와 동일한 stack 의미.
		std::unordered_map<uint32, FString> ForEachActorNodeIds;
		// exec 측에서 발급한 데이터-반환 노드의 local 변수명 (SpawnActor / Cast 등).
		// 노드의 Then exec 가 emit 되는 동안 GetOutputExpression 이 이 local 을 참조한다.
		std::unordered_map<uint32, FString> ExecLocals;
	};
}

FLuaBlueprintCompileResult FLuaBlueprintCompiler::Compile(const ULuaBlueprintAsset& Asset)
{
	FLuaBlueprintCompileResult Result;
	FCompilerContext Context(Asset, Result);
	Result.GeneratedLuaSource = Context.Compile();

	if (Asset.GetNodes().empty())
	{
		AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Warning, 0, "Blueprint has no nodes");
	}

	return Result;
}
